---

- name: Install epel repository
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install openldap required packages
  yum:
    name: "{{ openldap_packages }}"
    state: present
    update_cache: yes
  with_items: "{{ openldap_packages }}"

- name: Start and enable openldap service
  systemd:
    name: slapd
    state: started
    enabled: yes

- name: Enter ldap root password
  pause:
    prompt: "Please enter ldap root password"
    echo: no
  register: password_prompt

#- debug:
#    msg: "this is the entered password : {{ password_prompt.user_input }}"

- set_fact:
    ldap_rootpass: "{{ password_prompt.user_input }}"

- name: "Ansible | Print a message if a variable is undefined"
  debug:
    msg: "The 'ldap_rootpass' variable is undefined"
  when: ldap_rootpass is not defined

- name: Encrypt password
  command: "slappasswd -h {SSHA} -s {{ ldap_rootpass }}"
  register: encryption

- set_fact:
    ldap_encrypted_pass: "{{ encryption.stdout }}"

- name: ERROR | Encrypted ldap password not set
  debug:
    msg: "The 'ldap_encrypted_pass' variable is undefined"
  when: ldap_encrypted_pass is not defined

- debug:
    msg: "This is the encrypted password {{ ldap_encrypted_pass }}"

- name: Upload db.ldif file
  template:
    src: db.ldif.j2
    dest: "{{ slapd_path }}/db.ldif"
    backup: yes

- name: Upload monitor.ldif file
  template:
    src: monitor.ldif.j2
    dest: "{{ slapd_path }}/monitor.ldif"
    backup: yes

- name: Upload slapd_log.ldif file
  file:
    src: slapd_log.ldif
    dest: "{{ slapd_path }}/slapd_log.ldif"
    backup: yes

- name: Upload ldap_pass.ldif file
  template:
    src: ldap_pass.ldif.j2
    dest: "{{ slapd_path }}/ldap_pass.ldif"
    backup: yes

- name: Apply configuration changes
  command: " {{ item }}"
  loop:
    - "ldapmodify -Y EXTERNAL -H ldapi:/// -f {{ slapd_path }}/db.ldif"
    - "ldapmodify -Y EXTERNAL -H ldapi:/// -f {{ slapd_path }}/monitor.ldif"
    - "ldapmodify -Y EXTERNAL -H ldapi:/// -f {{ slapd_path }}/slapd_log.ldif"
    - "ldapmodify -Y EXTERNAL -H ldapi:/// -f {{ slapd_path }}/ldap_pass.ldif"

- name: Copy DB_CONFIG
  copy:
    src: /usr/share/openldap-servers/DB_CONFIG.example
    dest: /var/lib/ldap/DB_CONFIG
    remote_src: yes
    owner: ldap
    group: ldap

- name: Add cosine and nis ldap schemas
  command: "{{ item }}"
  loop:
    - ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
    - ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif
    - ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif

- name: Upload base.ldif template
  template:
    src: base.ldif.j2
    dest: "{{ slapd_path }}/base.ldif"
    backup: yes

- name: Apply the base.ldif configuration
  expect:
    command: "ldapadd -x -W -D \"cn={{ olc_rootDN }},dc={{ domain }},dc={{ domain_suffix }}\" -f {{ slapd_path }}/base.ldif"
    responses:
      Enter LDAP Password: "{{ ldap_rootpass }}"

- name: Upload ladp server rsyslog template
  template:
    src: 10-slapd.conf.j2
    dest: /etc/rsyslod.d/10-slapd.conf

- name: Restart rsyslog service
  systemd:
    name: rsyslog
    state: restarted

- import_tasks: ldap_client_config.yml
  tags:
    - ldap_client

- import_tasks: ldap_add_users.yml
  tags:
    - add_users
